secret: dongtaiwang.com
mixed-port: 7890
allow-lan: false
log-level: info
dns:
  enabled: true
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
proxies:
  - {"name":"dongtaiwang.com_1","type":"vmess","server":"104.19.58.70","port":8080,"cipher":"auto","uuid":"01c3345a-aadb-4e07-a920-947c20d83096","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"emily-citizen-oxford-gba.trycloudflare.com","network":"ws","ws-opts":{"path":"01c3345a-aadb-4e07-a920-947c20d83096-vm","headers":{"host":"emily-citizen-oxford-gba.trycloudflare.com"}}}
  - {"name":"dongtaiwang.com_2","type":"vmess","server":"yh7.freeh1.xyz","port":8080,"cipher":"auto","uuid":"01c3345a-aadb-4e07-a920-947c20d83096","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"emily-citizen-oxford-gba.trycloudflare.com","network":"ws","ws-opts":{"path":"01c3345a-aadb-4e07-a920-947c20d83096-vm","headers":{"host":"emily-citizen-oxford-gba.trycloudflare.com"}}}
  - {"name":"dongtaiwang.com_3","type":"vmess","server":"104.20.20.30","port":8080,"cipher":"auto","uuid":"01c3345a-aadb-4e07-a920-947c20d83096","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"emily-citizen-oxford-gba.trycloudflare.com","network":"ws","ws-opts":{"path":"01c3345a-aadb-4e07-a920-947c20d83096-vm","headers":{"host":"emily-citizen-oxford-gba.trycloudflare.com"}}}
  - {"name":"dongtaiwang.com_4","type":"vmess","server":"yh3.freeh1.xyz","port":8080,"cipher":"auto","uuid":"01c3345a-aadb-4e07-a920-947c20d83096","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"emily-citizen-oxford-gba.trycloudflare.com","network":"ws","ws-opts":{"path":"01c3345a-aadb-4e07-a920-947c20d83096-vm","headers":{"host":"emily-citizen-oxford-gba.trycloudflare.com"}}}
  - {"name":"dongtaiwang.com_5","type":"vmess","server":"yh4.dtku41.xyz","port":8080,"cipher":"auto","uuid":"01c3345a-aadb-4e07-a920-947c20d83096","alterId":0,"tls":false,"skip-cert-verify":true,"servername":"emily-citizen-oxford-gba.trycloudflare.com","network":"ws","ws-opts":{"path":"01c3345a-aadb-4e07-a920-947c20d83096-vm","headers":{"host":"emily-citizen-oxford-gba.trycloudflare.com"}}}
proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - DIRECT
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
      - dongtaiwang.com_5
  - name: ♻️ 自动选择
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
      - dongtaiwang.com_5
  - name: 🌍 国外媒体
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
      - dongtaiwang.com_5
  - name: 📲 电报信息
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
      - dongtaiwang.com_5
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 节点选择
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
      - dongtaiwang.com_5
  - name: 🍎 苹果服务
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
      - dongtaiwang.com_5
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - ♻️ 自动选择
  - name: 🛑 全球拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🍃 应用净化
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - ♻️ 自动选择
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
      - dongtaiwang.com_5
   

rules:
  - MATCH,🚀 节点选择
