secret: dongtaiwang.com
mixed-port: 7890
allow-lan: false
log-level: info
dns:
  enabled: true
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
proxies:
  - name: dongtaiwang.com_0                     
    server: 62.210.10.113
    port: 33998
    type: tuic
    uuid: 909212b8-5d67-4532-885e-7a6b5e724ab8
    password: dongtaiwang.com
    alpn: [h3]
    sni: bing.com
    skip-cert-verify: true
    reduce-rtt: true
    udp-relay-mode: native
    congestion-controller: bbr
  - name: dongtaiwang.com_1                     
    server: 2001:bc8:32d7:306::123
    port: 33998
    type: tuic
    uuid: 909212b8-5d67-4532-885e-7a6b5e724ab8
    password: dongtaiwang.com
    alpn: [h3]
    sni: bing.com
    skip-cert-verify: true
    reduce-rtt: true
    udp-relay-mode: native
    congestion-controller: bbr
  - name: dongtaiwang.com_2                     
    server: 2001:bc8:32d7:306::124
    port: 33998
    type: tuic
    uuid: 909212b8-5d67-4532-885e-7a6b5e724ab8
    password: dongtaiwang.com
    alpn: [h3]
    sni: bing.com
    skip-cert-verify: true
    reduce-rtt: true
    udp-relay-mode: native
    congestion-controller: bbr
  - name: dongtaiwang.com_3                     
    server: 2001:bc8:32d7:306::125
    port: 33998
    type: tuic
    uuid: 909212b8-5d67-4532-885e-7a6b5e724ab8
    password: dongtaiwang.com
    alpn: [h3]
    sni: bing.com
    skip-cert-verify: true
    reduce-rtt: true
    udp-relay-mode: native
    congestion-controller: bbr
  - name: dongtaiwang.com_4                     
    server: 2001:bc8:32d7:306::126
    port: 33998
    type: tuic
    uuid: 909212b8-5d67-4532-885e-7a6b5e724ab8
    password: dongtaiwang.com
    alpn: [h3]
    sni: bing.com
    skip-cert-verify: true
    reduce-rtt: true
    udp-relay-mode: native
    congestion-controller: bbr
proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - ♻️ 自动选择
      - DIRECT
      - dongtaiwang.com_0
  - name: ♻️ 自动选择
    type: fallback              
    url: "https://www.gstatic.com/generate_204"
    interval: 5
    proxies:
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
  - name: 🌍 国外媒体
    type: select
    proxies:
      - 🚀 节点选择
      - ♻️ 自动选择
      - 🎯 全球直连
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
  - name: 📲 电报信息
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
  - name: Ⓜ️ 微软服务
    type: select
    proxies:
      - 🎯 全球直连
      - 🚀 节点选择
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
  - name: 🍎 苹果服务
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
  - name: 🎯 全球直连
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - ♻️ 自动选择
  - name: 🛑 全球拦截
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🍃 应用净化
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 节点选择
      - 🎯 全球直连
      - ♻️ 自动选择
      - dongtaiwang.com_0
      - dongtaiwang.com_1
      - dongtaiwang.com_2
      - dongtaiwang.com_3
      - dongtaiwang.com_4
rules:
  - MATCH,🚀 节点选择
